version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      # install jekyll
      - gem install jekyll bundler
  pre_build:
    commands:
      - curl -OL https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar
      - git clone https://github.com/HealthDataWorks/fhir-ig-template-base.git custom-template
  build:
    commands:
      - export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
      - java -jar publisher.jar -ig ig.ini
  post_build:
    commands:
      - echo Delete S3 Bucket object...
      - aws s3 rm s3://${S3_BUCKET_NAME} --recursive
artifacts:
  files:
    - '**/*'
  base-directory: output
